name: Playwright BDD Tests

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browser
      run: npx playwright install chromium

    - name: Run Cucumber Tests
      run: |
        echo "Starting Tests..."
        npx cucumber-js --format progress --format summary
        echo "Tests Completed"

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30